version: "3.5"
services:
  portal-ett:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: portaldbett
      POSTGRES_PASSWORD: Ett@2024
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
